#!/usr/bin/env python3
# Generates base/screens/snake.yaml (modular carousel screen, base id 9). Run from anywhere:
#   python scripts/gen_snake.py
# Snake on a 12x12 grid, knob steers (rotate = quarter-turn). Body = pool of obj widgets
# (LVGL can't address a widget by a runtime index, so we keep N segment widgets and set
# each one's position/visibility from the g_sn_x/g_sn_y arrays every move).
import os

POOL = 32          # max snake length = number of segment widgets
GRID = 12          # 12x12 cells
CELL = 20          # px per cell  -> field 240px, centre = i*20-110  (i 0..11 -> -110..110)
OFF  = (GRID * CELL) // 2 - CELL // 2   # 110

HEAD = "0x9BF7B0"
BODY = "0x35C46B"
FOOD = "0xFF5D5D"

def seg_widgets():
    out = []
    for i in range(POOL):
        col = HEAD if i == 0 else BODY
        out.append(
            f"        - obj: {{ id: sn_s{i}, align: CENTER, x: 0, y: 0, width: 18, height: 18, "
            f"radius: 4, border_width: 0, bg_color: {col}, bg_opa: COVER, hidden: true }}"
        )
    return "\n".join(out)

def seg_updates():
    out = []
    for i in range(POOL):
        out.append(
f"""      - lvgl.widget.update:
          id: sn_s{i}
          hidden: !lambda 'return id(g_sn_len) <= {i};'
          x: !lambda 'return id(g_sn_x)[{i}] * {CELL} - {OFF};'
          y: !lambda 'return id(g_sn_y)[{i}] * {CELL} - {OFF};'""")
    return "\n".join(out)

def seg_hides():
    return "\n".join(f"      - lvgl.widget.hide: sn_s{i}" for i in range(POOL))

YAML = f"""# Snake - optional carousel screen (base id 9). Grid snake steered by the knob.
# Remove it: drop this file from your config's package "files:" list. Nothing else to edit.
# Scores (g_sn_top / g_sn_best) + the "Reset scores" settings action live here - fully self-contained.
#
# This file is generated by scripts/gen_snake.py (the {POOL}-segment body pool + its per-move
# updates are repetitive). Edit the generator, not the blocks, when changing pool/grid size.

esphome:
  on_boot:
    - priority: 655
      then:
        - lambda: 'id(g_present)[9] = true;'   # register after clock/player/timer/cars/space
    # Settings (Settings -> Widgets -> Snake -> Reset scores) + factory-reset handling.
    - priority: 650
      then:
        - lambda: |-
            int g = id(g_wgrp_n)++;
            id(g_wgrp_labels) += (g ? "\\n" : ""); id(g_wgrp_labels) += "Snake";
            int o = id(g_wopt_n)++;
            id(g_wopt_group)[o] = g; id(g_wopt_label)[o] = "Reset scores"; id(g_wopt_kind)[o] = 1; id(g_wopt_ptr)[o] = &id(g_sn_reset);

globals:
  # --- scores (persistent) + reset flag, owned by this package ---
  - id: g_sn_best
    type: int
    restore_value: yes
    initial_value: '0'
  - id: g_sn_top
    type: int[10]
    restore_value: yes
  - id: g_sn_reset    # Widgets "Reset scores" sets this; the watcher below clears the scores
    type: bool
    restore_value: no
    initial_value: 'false'
  # --- Snake game (page_snake, g_base==9) ---
  - id: g_sn_state    # 0=menu 1=playing 2=game over 3=how-to 4=scores
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_dir      # heading: 0=up 1=right 2=down 3=left
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_len      # current snake length (number of live segments)
    type: int
    restore_value: no
    initial_value: '3'
  - id: g_sn_score
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_x        # body cell columns (0..{GRID-1}); [0] = head
    type: int[{POOL}]
    restore_value: no
  - id: g_sn_y        # body cell rows
    type: int[{POOL}]
    restore_value: no
  - id: g_sn_fx       # food cell
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_fy
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_acc      # sub-tick accumulator (50ms ticks); a move happens every g_sn_period ticks
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_sn_period   # ticks between moves (lower = faster); starts 5 (250ms), min 2 (100ms)
    type: int
    restore_value: no
    initial_value: '5'
  - id: g_sn_dead     # set by the move lambda on wall/self hit
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: g_sn_need_food  # set by the move lambda when an apple was eaten -> respawn after
    type: bool
    restore_value: no
    initial_value: 'false'

script:
  # Place an apple on a random free cell (not under the snake).
  - id: sn_place_food
    then:
      - lambda: |-
          bool ok = false; int fx = 0, fy = 0, tries = 0;
          while (!ok && tries < 400) {{
            fx = esp_random() % {GRID}; fy = esp_random() % {GRID}; tries++;
            ok = true;
            for (int i = 0; i < id(g_sn_len); i++)
              if (id(g_sn_x)[i] == fx && id(g_sn_y)[i] == fy) {{ ok = false; break; }}
          }}
          id(g_sn_fx) = fx; id(g_sn_fy) = fy;
  # HUD: current score (top of the screen).
  - id: sn_hud
    then:
      - lvgl.label.update: {{ id: lbl_sn_score, text: !lambda 'char b[12]; snprintf(b,sizeof(b),"%d",id(g_sn_score)); return std::string(b);' }}
  # Draw the apple + every body segment (visible ones placed, the rest hidden).
  - id: sn_draw
    then:
      - lvgl.widget.update:
          id: sn_food
          hidden: false
          x: !lambda 'return id(g_sn_fx) * {CELL} - {OFF};'
          y: !lambda 'return id(g_sn_fy) * {CELL} - {OFF};'
{seg_updates()}
  # Hide the whole body + apple (used when leaving the play state).
  - id: sn_clear
    then:
{seg_hides()}
      - lvgl.widget.hide: sn_food
  # Start / restart a game.
  - id: sn_start
    then:
      - lambda: |-
          id(g_sn_state) = 1; id(g_sn_score) = 0; id(g_sn_dead) = false;
          id(g_sn_len) = 3; id(g_sn_dir) = 0;            // heading up
          id(g_sn_x)[0] = 6; id(g_sn_y)[0] = 6;          // head, centre-ish
          id(g_sn_x)[1] = 6; id(g_sn_y)[1] = 7;
          id(g_sn_x)[2] = 6; id(g_sn_y)[2] = 8;
          id(g_sn_acc) = 0; id(g_sn_period) = 5; id(g_sn_need_food) = false;
          id(g_knob_capture) = true; id(g_knob_delta) = 0;
      - script.execute: sn_place_food
      - script.execute: sn_screen
      - script.execute: sn_draw
      - script.execute: sn_hud
  # Game over: release the knob, save the score into best + top 10.
  - id: sn_over
    then:
      - lambda: |-
          id(g_sn_state) = 2; id(g_knob_capture) = false;
          int s = id(g_sn_score);
          if (s > id(g_sn_best)) id(g_sn_best) = s;
          for (int i = 0; i < 10; i++) {{
            if (s > id(g_sn_top)[i]) {{
              for (int j = 9; j > i; j--) id(g_sn_top)[j] = id(g_sn_top)[j-1];
              id(g_sn_top)[i] = s;
              break;
            }}
          }}
      - script.execute: sn_screen
  # Show the right widgets for the current state (mirrors cool-cars' game_screen).
  - id: sn_screen
    then:
      # 1) hide everything
      - lvgl.widget.hide: sn_field
      - script.execute: sn_clear
      - lvgl.widget.hide: lbl_sn_score
      - lvgl.widget.hide: lbl_sn_title
      - lvgl.widget.hide: lbl_sn_hint
      - lvgl.widget.hide: btn_sn_start
      - lvgl.widget.hide: btn_sn_howto
      - lvgl.widget.hide: btn_sn_scores
      - lvgl.widget.hide: lbl_sn_over
      - lvgl.widget.hide: lbl_sn_rec
      - lvgl.widget.hide: btn_sn_replay
      - lvgl.widget.hide: btn_sn_exit
      - lvgl.widget.hide: lbl_sn_howto_t
      - lvgl.widget.hide: lbl_sn_howto1
      - lvgl.widget.hide: lbl_sn_howto2
      - lvgl.widget.hide: lbl_sn_howto3
      - lvgl.widget.hide: lbl_sn_scores_t
      - lvgl.widget.hide: lbl_sn_scores1
      - lvgl.widget.hide: lbl_sn_scores2
      - lvgl.widget.hide: btn_sn_back
      # 2) show per state
      - if:   # MENU
          condition: {{ lambda: 'return id(g_sn_state) == 0;' }}
          then:
            - lvgl.widget.show: lbl_sn_title
            - lvgl.widget.show: lbl_sn_hint
            - lvgl.widget.show: btn_sn_start
            - lvgl.widget.show: btn_sn_howto
            - lvgl.widget.show: btn_sn_scores
      - if:   # PLAY
          condition: {{ lambda: 'return id(g_sn_state) == 1;' }}
          then:
            - lvgl.widget.show: sn_field
            - lvgl.widget.show: lbl_sn_score
            - script.execute: sn_draw
      - if:   # GAME OVER
          condition: {{ lambda: 'return id(g_sn_state) == 2;' }}
          then:
            - lvgl.widget.show: lbl_sn_over
            - lvgl.widget.show: lbl_sn_rec
            - lvgl.widget.show: btn_sn_replay
            - lvgl.widget.show: btn_sn_exit
            - lvgl.label.update: {{ id: lbl_sn_over, text: !lambda 'char b[24]; snprintf(b,sizeof(b),"Score: %d", id(g_sn_score)); return std::string(b);' }}
            - lvgl.label.update: {{ id: lbl_sn_rec,  text: !lambda 'char b[24]; snprintf(b,sizeof(b),"Best: %d", id(g_sn_best)); return std::string(b);' }}
      - if:   # HOW TO PLAY
          condition: {{ lambda: 'return id(g_sn_state) == 3;' }}
          then:
            - lvgl.widget.show: lbl_sn_howto_t
            - lvgl.widget.show: lbl_sn_howto1
            - lvgl.widget.show: lbl_sn_howto2
            - lvgl.widget.show: lbl_sn_howto3
            - lvgl.widget.show: btn_sn_back
      - if:   # SCORES (top 10)
          condition: {{ lambda: 'return id(g_sn_state) == 4;' }}
          then:
            - lvgl.widget.show: lbl_sn_scores_t
            - lvgl.widget.show: lbl_sn_scores1
            - lvgl.widget.show: lbl_sn_scores2
            - lvgl.widget.show: btn_sn_back
            - lvgl.label.update:
                id: lbl_sn_scores1
                text: !lambda |-
                  std::string s; char b[24];
                  for (int i = 0; i < 5; i++) {{ if(i) s += "\\n"; if(id(g_sn_top)[i]>0){{ snprintf(b,sizeof(b),"%d.  %d",i+1,id(g_sn_top)[i]); }} else {{ snprintf(b,sizeof(b),"%d.  -",i+1); }} s += b; }}
                  return s;
            - lvgl.label.update:
                id: lbl_sn_scores2
                text: !lambda |-
                  std::string s; char b[24];
                  for (int i = 5; i < 10; i++) {{ if(i>5) s += "\\n"; if(id(g_sn_top)[i]>0){{ snprintf(b,sizeof(b),"%d.  %d",i+1,id(g_sn_top)[i]); }} else {{ snprintf(b,sizeof(b),"%d.  -",i+1); }} s += b; }}
                  return s;

interval:
  # Reset scores when the Widgets action fired (g_sn_reset) or on factory reset.
  - interval: 250ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_sn_reset) || id(g_factory_reset);' }}
          then:
            - lambda: 'for (int i = 0; i < 10; i++) id(g_sn_top)[i] = 0; id(g_sn_best) = 0; id(g_sn_reset) = false;'
  # nav: show this screen when it is selected in the carousel
  - interval: 50ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_nav_req) && id(g_base)==9;' }}
          then:
            - lambda: 'id(g_nav_req) = false; id(g_sn_state) = 0; id(g_knob_capture) = false;'
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==0;' }}, then: [lvgl.page.show: {{ id: page_snake, animation: move_left,   time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==1;' }}, then: [lvgl.page.show: {{ id: page_snake, animation: move_right,  time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==2;' }}, then: [lvgl.page.show: {{ id: page_snake, animation: move_top,    time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==3;' }}, then: [lvgl.page.show: {{ id: page_snake, animation: move_bottom, time: 250ms }}] }}
            - script.execute: sn_screen
  # Game tick: steer with the knob, step the snake every g_sn_period ticks.
  - interval: 50ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_base) == 9 && id(g_sn_state) == 1;' }}
          then:
            - lambda: 'id(g_sn_acc)++;'
            - if:
                condition: {{ lambda: 'return id(g_sn_acc) >= id(g_sn_period);' }}
                then:
                  - lambda: |-
                      id(g_sn_acc) = 0;
                      // steer: net knob rotation -> at most one quarter turn (so you can never reverse into yourself)
                      int kd = id(g_knob_delta); id(g_knob_delta) = 0;
                      if (kd > 0) id(g_sn_dir) = (id(g_sn_dir) + 1) % 4;
                      else if (kd < 0) id(g_sn_dir) = (id(g_sn_dir) + 3) % 4;
                      // next head cell
                      int nx = id(g_sn_x)[0], ny = id(g_sn_y)[0], dir = id(g_sn_dir);
                      if (dir == 0) ny -= 1; else if (dir == 1) nx += 1; else if (dir == 2) ny += 1; else nx -= 1;
                      if (nx < 0 || nx >= {GRID} || ny < 0 || ny >= {GRID}) {{ id(g_sn_dead) = true; }}
                      else {{
                        bool grow = (nx == id(g_sn_fx) && ny == id(g_sn_fy));
                        // self-hit: check the cells that will still be occupied (the tail vacates unless we grow)
                        int checkN = id(g_sn_len) - (grow ? 0 : 1);
                        bool hit = false;
                        for (int i = 0; i < checkN; i++) if (id(g_sn_x)[i] == nx && id(g_sn_y)[i] == ny) {{ hit = true; break; }}
                        if (hit) {{ id(g_sn_dead) = true; }}
                        else {{
                          int newlen = id(g_sn_len) + (grow ? 1 : 0);
                          if (newlen > {POOL}) newlen = {POOL};
                          for (int i = newlen - 1; i > 0; i--) {{ id(g_sn_x)[i] = id(g_sn_x)[i-1]; id(g_sn_y)[i] = id(g_sn_y)[i-1]; }}
                          id(g_sn_x)[0] = nx; id(g_sn_y)[0] = ny;
                          id(g_sn_len) = newlen;
                          if (grow) {{
                            id(g_sn_score) += 10;
                            id(g_sn_need_food) = true;
                            int p = 5 - id(g_sn_score) / 80; if (p < 2) p = 2; id(g_sn_period) = p;   // speed up
                          }}
                        }}
                      }}
                  - if:
                      condition: {{ lambda: 'return id(g_sn_dead);' }}
                      then:
                        - script.execute: sn_over
                      else:
                        - if:
                            condition: {{ lambda: 'return id(g_sn_need_food);' }}
                            then:
                              - lambda: 'id(g_sn_need_food) = false;'
                              - script.execute: sn_place_food
                              - script.execute: sn_hud
                        - script.execute: sn_draw

lvgl:
  pages:
    # --- SNAKE page (base id 9): 12x12 grid, knob steers ---
    - id: page_snake
      bg_color: 0x07120F
      scrollbar_mode: "off"
      scrollable: false
      widgets:
        # play field frame (240x240, fits inside the round display)
        - obj: {{ id: sn_field, align: CENTER, x: 0, y: 0, width: 244, height: 244, radius: 14, bg_color: 0x0C1A14, bg_opa: COVER, border_width: 2, border_color: 0x1C3A2C, hidden: true }}
        # apple + body segment pool ({POOL} max). sn_s0 = head (brighter).
        - obj: {{ id: sn_food, align: CENTER, x: 0, y: 0, width: 16, height: 16, radius: 8, border_width: 0, bg_color: {FOOD}, bg_opa: COVER, hidden: true }}
{seg_widgets()}
        # HUD
        - label: {{ id: lbl_sn_score, align: CENTER, x: 0, y: -150, text: "0", text_font: font_med, text_color: 0xCFEAE4, hidden: true }}
        # --- MENU (state 0): wordmark up top, 3 stacked buttons (same geometry as the other games) ---
        - label: {{ id: lbl_sn_title, align: CENTER, x: 0, y: -78, text: "SNAKE", text_font: font_sel, text_color: 0x6EE7A0, hidden: true }}
        - label: {{ id: lbl_sn_hint, align: CENTER, x: 0, y: -44, text: "turn the knob to steer", text_font: font_artist, text_color: 0x6F8A80, hidden: true }}
        - button:
            id: btn_sn_start
            align: CENTER
            y: 4
            width: 150
            height: 44
            radius: 22
            bg_color: 0x2FE6CF
            bg_opa: COVER
            border_width: 0
            on_click: [ script.execute: sn_start ]
            widgets:
              - label: {{ align: CENTER, text: "Start", text_font: font_med, text_color: 0x06201C }}
        - button:
            id: btn_sn_howto
            align: CENTER
            y: 54
            width: 150
            height: 44
            radius: 22
            bg_color: 0x183A2C
            bg_opa: COVER
            border_width: 0
            on_click: [ lambda: 'id(g_sn_state) = 3;', script.execute: sn_screen ]
            widgets:
              - label: {{ align: CENTER, text: "How to play?", text_font: font_med, text_color: 0xCFEAE4 }}
        - button:
            id: btn_sn_scores
            align: CENTER
            y: 104
            width: 150
            height: 44
            radius: 22
            bg_color: 0x183A2C
            bg_opa: COVER
            border_width: 0
            on_click: [ lambda: 'id(g_sn_state) = 4;', script.execute: sn_screen ]
            widgets:
              - label: {{ align: CENTER, text: "Scores", text_font: font_med, text_color: 0xCFEAE4 }}
        # --- GAME OVER (state 2) ---
        - label: {{ id: lbl_sn_over, align: CENTER, x: 0, y: -10, text_align: CENTER, text: "", text_font: font_sel, text_color: 0xFFFFFF, hidden: true }}
        - label: {{ id: lbl_sn_rec, align: CENTER, x: 0, y: 22, text_align: CENTER, text: "", text_font: font_artist, text_color: 0x9AA6B2, hidden: true }}
        - button:
            id: btn_sn_replay
            align: CENTER
            x: -66
            y: 62
            width: 112
            height: 48
            radius: 24
            bg_color: 0x2FE6CF
            bg_opa: COVER
            border_width: 0
            hidden: true
            on_click: [ script.execute: sn_start ]
            widgets:
              - label: {{ align: CENTER, text: "Play", text_font: font_med, text_color: 0x06201C }}
        - button:
            id: btn_sn_exit
            align: CENTER
            x: 66
            y: 62
            width: 112
            height: 48
            radius: 24
            bg_color: 0x3A3A3D
            bg_opa: COVER
            border_width: 0
            hidden: true
            on_click: [ lambda: 'id(g_sn_state) = 0;', script.execute: sn_screen ]
            widgets:
              - label: {{ align: CENTER, text: "Exit", text_font: font_med, text_color: 0xFFFFFF }}
        # --- HOW TO PLAY (state 3) ---
        - label: {{ id: lbl_sn_howto_t, align: CENTER, y: -104, text: "HOW TO PLAY?", text_font: font_sel, text_color: 0xE94FB0, hidden: true }}
        - label: {{ id: lbl_sn_howto1, align: CENTER, y: -44, text: "Turn the knob to steer", text_font: font_med, text_color: 0xC2CDDA, hidden: true }}
        - label: {{ id: lbl_sn_howto2, align: CENTER, y: -8, text: "Eat the red apples", text_font: font_med, text_color: 0xC2CDDA, hidden: true }}
        - label: {{ id: lbl_sn_howto3, align: CENTER, y: 28, text: "Avoid the walls & your tail", text_font: font_med, text_color: 0xC2CDDA, hidden: true }}
        # --- SCORES (state 4): top 10 in two columns ---
        - label: {{ id: lbl_sn_scores_t, align: CENTER, y: -116, text: "SCORES", text_font: font_sel, text_color: 0xE94FB0, hidden: true }}
        - label: {{ id: lbl_sn_scores1, align: CENTER, x: -52, y: 0, text: "", text_align: LEFT, text_font: font_artist, text_color: 0xC2CDDA, hidden: true }}
        - label: {{ id: lbl_sn_scores2, align: CENTER, x: 56, y: 0, text: "", text_align: LEFT, text_font: font_artist, text_color: 0xC2CDDA, hidden: true }}
        # --- Back (state 3/4 -> menu) ---
        - button:
            id: btn_sn_back
            align: CENTER
            y: 120
            width: 130
            height: 42
            radius: 21
            bg_color: 0x3A3A3D
            bg_opa: COVER
            border_width: 0
            hidden: true
            on_click: [ lambda: 'id(g_sn_state) = 0;', script.execute: sn_screen ]
            widgets:
              - label: {{ align: CENTER, text: "Back", text_font: font_med, text_color: 0xFFFFFF }}
"""

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", "base", "screens", "snake.yaml")
out = os.path.normpath(out)
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write(YAML)
print("wrote", out, "(", len(YAML), "bytes )")
